# 기본 설정
producer_topic: "OrderbookPreprocessing"
group_id: "orderbook"

# 재시도 설정
max_retries: 3
retry_min_wait: 4
retry_max_wait: 10

# 로깅 설정
log_level: "INFO"
log_file: "orderbook_processor.log"

# 거래소별 설정
exchanges:
  # 한국 거래소
  korea:
    upbit:
      partition: 1
    bithumb:
      partition: 3
    coinone:
      partition: 5
    korbit:
      partition: 7
  
  # 아시아 거래소
  asia:
    okx:
      partition: 1
    bybit:
      partition: 3
    gateio:
      partition: 5
  
  # 북유럽 거래소
  ne:
    binance:
      partition: 1
    kraken:
      partition: 3
